version: '3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret

  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  db:
    image: mysql:5.7
    container_name: my-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
